package malt

import "fmt"

// InclusionProof proves a leaf at Index exists in a tree of TreeSize.
//
// Generated by [Log.InclusionProof] and verified by [VerifyInclusion].
type InclusionProof[D comparable] struct {
	// Index is the 0-based leaf index.
	Index uint64
	// TreeSize is the size of the tree for which this proof is valid.
	TreeSize uint64
	// Path contains the sibling hashes from leaf to root.
	Path []D
}

// ConsistencyProof proves a tree of OldSize is a prefix of NewSize.
//
// Generated by [Log.ConsistencyProof] and verified by [VerifyConsistency].
type ConsistencyProof[D comparable] struct {
	// OldSize is the size of the older tree.
	OldSize uint64
	// NewSize is the size of the newer tree.
	NewSize uint64
	// Path contains the intermediate hashes.
	Path []D
}

// InclusionProof generates an inclusion proof for the leaf at index
// (formal model §4.2).
//
// The proof demonstrates that the leaf at index exists in the current tree.
// Verify with [VerifyInclusion].
func (l *Log[D]) InclusionProof(index uint64) (*InclusionProof[D], error) {
	if l.size == 0 {
		return nil, ErrEmptyTree
	}
	if index >= l.size {
		return nil, fmt.Errorf("%w: index %d >= tree_size %d", ErrIndexOutOfBounds, index, l.size)
	}
	path := l.genPath(int(index), l.leaves)
	return &InclusionProof[D]{
		Index:    index,
		TreeSize: l.size,
		Path:     path,
	}, nil
}

// ConsistencyProof generates a consistency proof from oldSize to the
// current size (formal model §5.2).
//
// The proof demonstrates that the tree at oldSize is a prefix of the
// current tree. Verify with [VerifyConsistency].
func (l *Log[D]) ConsistencyProof(oldSize uint64) (*ConsistencyProof[D], error) {
	if l.size == 0 {
		return nil, ErrEmptyTree
	}
	if oldSize == 0 || oldSize >= l.size {
		return nil, fmt.Errorf("%w: old_size %d, new_size %d", ErrInvalidOldSize, oldSize, l.size)
	}
	path := l.subproof(int(oldSize), l.leaves, true)
	return &ConsistencyProof[D]{
		OldSize: oldSize,
		NewSize: l.size,
		Path:    path,
	}, nil
}

// genPath implements the PATH algorithm for inclusion proofs (§4.2).
//
// Recursively computes the sibling hashes from leaf m to the root.
func (l *Log[D]) genPath(m int, leaves []D) []D {
	n := len(leaves)
	if n == 1 {
		// P-BASE: single leaf, no siblings needed.
		return nil
	}
	k := largestPow2LessThan(n)
	if m < k {
		// P-LEFT: leaf is in the left (complete) subtree.
		result := l.genPath(m, leaves[:k])
		return append(result, mth(l.hasher, leaves[k:]))
	}
	// P-RIGHT: leaf is in the right subtree.
	result := l.genPath(m-k, leaves[k:])
	return append(result, mth(l.hasher, leaves[:k]))
}

// subproof implements the SUBPROOF algorithm for consistency proofs (§5.2).
//
// Recursively computes the intermediate hashes proving that the first m
// leaves are a prefix of the leaves slice.
func (l *Log[D]) subproof(m int, leaves []D, b bool) []D {
	n := len(leaves)
	if m == n {
		if b {
			// C-SAME: old tree equals current subtree, flag is true.
			return nil
		}
		// C-HASH: old tree equals current subtree, flag is false.
		return []D{mth(l.hasher, leaves)}
	}
	k := largestPow2LessThan(n)
	if m <= k {
		// C-LEFT: old size fits within left subtree.
		result := l.subproof(m, leaves[:k], b)
		return append(result, mth(l.hasher, leaves[k:]))
	}
	// C-RIGHT: old size exceeds left subtree.
	result := l.subproof(m-k, leaves[k:], false)
	return append(result, mth(l.hasher, leaves[:k]))
}

// VerifyInclusion verifies an inclusion proof (formal model §4.3).
//
// Returns true if the proof demonstrates that leafHash is the leaf at
// proof.Index in a tree of proof.TreeSize with the given root.
//
// This is a standalone verifier — no [Log] is needed.
func VerifyInclusion[D comparable](hasher TreeHasher[D], leafHash D, proof *InclusionProof[D], root D) bool {
	if proof.Index >= proof.TreeSize {
		return false
	}

	fn := proof.Index
	sn := proof.TreeSize - 1
	r := leafHash

	for _, p := range proof.Path {
		if sn == 0 {
			return false
		}
		if fn&1 == 1 || fn == sn {
			r = hasher.Node(p, r)
			for fn&1 == 0 && fn != 0 {
				fn >>= 1
				sn >>= 1
			}
		} else {
			r = hasher.Node(r, p)
		}
		fn >>= 1
		sn >>= 1
	}

	return sn == 0 && r == root
}

// VerifyConsistency verifies a consistency proof (formal model §5.3).
//
// Returns true if the proof demonstrates that the tree of proof.OldSize
// with oldRoot is a prefix of the tree of proof.NewSize with newRoot.
//
// This is a standalone verifier — no [Log] is needed.
func VerifyConsistency[D comparable](hasher TreeHasher[D], proof *ConsistencyProof[D], oldRoot, newRoot D) bool {
	if proof.OldSize == 0 || proof.OldSize >= proof.NewSize {
		return false
	}

	// Build the effective path: if OldSize is a power of 2, prepend oldRoot.
	var path []D
	if isPowerOfTwo(proof.OldSize) {
		path = make([]D, 1+len(proof.Path))
		path[0] = oldRoot
		copy(path[1:], proof.Path)
	} else {
		path = proof.Path
	}

	if len(path) == 0 {
		return false
	}

	fn := proof.OldSize - 1
	sn := proof.NewSize - 1

	// Strip common prefix of trailing ones.
	for fn&1 == 1 {
		fn >>= 1
		sn >>= 1
	}

	fr := path[0]
	sr := path[0]

	for _, c := range path[1:] {
		if sn == 0 {
			return false
		}
		if fn&1 == 1 || fn == sn {
			fr = hasher.Node(c, fr)
			sr = hasher.Node(c, sr)
			for fn&1 == 0 && fn != 0 {
				fn >>= 1
				sn >>= 1
			}
		} else {
			sr = hasher.Node(sr, c)
		}
		fn >>= 1
		sn >>= 1
	}

	return sn == 0 && fr == oldRoot && sr == newRoot
}

// isPowerOfTwo reports whether n is a power of two.
func isPowerOfTwo(n uint64) bool {
	return n > 0 && n&(n-1) == 0
}
